### ISSUE TITLE
Change the "global RIPE" behavior

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-sdk-components-vue#39]
## Description

Using SDK components, it should be possible to:
- Have a working page without ever manually instantiating a RIPE SDK
- Be able to instantiate a RIPE SDK and use it on-demand

Both of these were solved by using `global.ripe`. However, the [implementation](https://github.com/ripe-tech/ripe-sdk-components-vue/blob/master/vue/mixins/logic.js) has a few problems that must be address in order to make it easy to use.

Change the behavior so that:
- `config=true` & `ripe=something`: uses the instance being passed and configs it if needed (done)
- `config=true` & `ripe=null`: initializes a new SDK and configs it (missing) setting it as the global one in case no global ripe is set
- `config=false` & `ripe=something`: uses the instance being passed and does nothing. **Could eventually sync its state to match the SDK's (change `data` and emit `update:x` events)** (done)
- `config=false` & `ripe=null`: uses `global.ripe` and does nothing. **Could eventually sync its state to match the SDK's (change `data` and emit `update:x` events)** (missing)

[`config`](https://github.com/ripe-tech/ripe-sdk-components-vue/blob/c17e9a2bd7a79ae77722dced406ec4df070de00f/vue/components/organisms/ripe-configurator/ripe-configurator.vue#L100) uses the configuration being passed, which [includes](https://github.com/ripe-tech/ripe-sdk-components-vue/blob/c17e9a2bd7a79ae77722dced406ec4df070de00f/vue/mixins/logic.js#L36):
- brand
- model
- parts
- currency

... and must also include:
- variant
- initialsExtra ([sort of included](https://github.com/ripe-tech/ripe-sdk-components-vue/blob/c17e9a2bd7a79ae77722dced406ec4df070de00f/vue/components/organisms/ripe-image/ripe-image.vue#L121), but must be more global so that other stuff such as `price-ripe` can use it)
- [structure](https://github.com/ripe-tech/ripe-sdk/blob/be944a8a361b0a36f17effb05e66c53fe8de593b/src/js/base/ripe.js#L57), which is sort of a view over the above and must also be accepted as `prop` since it's the easiest way to clients to transport RIPE SDK state around (with `getStructure`/`fromStructure`/`setStructure`)

**Comment by joamag** [comment]
@gcandal the only behavior that has to be "fixed" (as talked before) is the fact that if the `window.ripe` instance is already defined should not be "re-set". Apart from that everything should be working now.

This is assuming that `config=false` and `ripe=null` is already working as you describe (expected)

**Comment by joamag** [comment]
@gcandal try to pick this up yourself so that we can properly fix this dev experience

**Comment by joamag** [comment]
@gcandal let's generalize the code (mixin) and add support for:

* `structure`
* `initialsExtra`

**Comment by joamag** [comment]
@gcandal please review if everything works as expected and close this issue if that's the case

**Comment by gcandal** [comment]
@3rdvision @NFSS10update your ripe-sdk-components-vue to 0.2.0 and check if everything is still working.

@BeeMargaridadouble-check it as well, since you're already familiar with testing more intricate scenarios.

**Comment by BeeMargarida** [comment]
> @3rdvision @NFSS10update your ripe-sdk-components-vue to 0.2.0 and check if everything is still working.
> 
> @BeeMargaridadouble-check it as well, since you're already familiar with testing more intricate scenarios.

I noticed a small problem in a specific use case where after changing to another model using `structure`, we change to another and provided `initials` and `parts` in the `structure`, which were not being applied. Will open a PR with the fix

**Comment by gcandal** [comment]
Closing this since @BeeMargarida 's comment has already an associated PR (https://github.com/ripe-tech/ripe-sdk-components-vue/pull/48).

Opening a new issue to deal with the backport so we can better manage priorities: https://github.com/ripe-tech/ripe-sdk-components-react/issues/33
