### ISSUE TITLE
Configurator destruction causing errors

### ISSUE THREAD

**Issue by BeeMargarida** [ripe-tech/ripe-sdk-components-vue#45]
## Description

When switching between `ripe-configurator` story and others several times, errors of `this.element is null` start to appear in the console. This might be due to the fact that unresolved promises and timeouts are still hanging in the `configurator-prc` of `ripe-sdk`.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The configurator destroys without causing any errors. |
| **Observed** | Errors appear if the there are very fast switches between configurator and other elements. |

## Repro Steps

1. Go to the storybook of `ripe-sdk-components-vue` https://ripe-sdk-components-vue.platforme.com/storybook
2. Switch fast between `ripe-configurator` and others components several times
3. The error will appear

## Environment

| Key | Value |
| --- | --- |
| **Device** | Desktop |
| **Operating System** | Manjaro Linux |
| **Browser** | Firefox 83.0 |
| **Instance (URL)** | https://ripe-sdk-components-vue.platforme.com/storybook |

## Screens

```
Uncaught (in promise) TypeError: this.element is null
    mark configurator-prc.js:1305
    render configurator-prc.js:1351
    promise callback*render configurator-prc.js:1351
    render configurator-prc.js:1353
    render configurator-prc.js:1353
    result configurator-prc.js:1369
    setTimeout handler*./node_modules/ripe-sdk/src/js/visual/configurator-prc.js/ripe.ConfiguratorPrc.prototype._preload/result< configurator-prc.js:1367
    _preload configurator-prc.js:1276
    update configurator-prc.js:247
    _update ripe.js:1256
    update ripe.js:1315
    setPart ripe.js:716
    _callee2$ ripe-pickers.vue:185
    Babel 8
    VueJS 3
configurator-prc.js:1305

```
![sdk-element-error-deploy](https://user-images.githubusercontent.com/25725586/101146096-84304800-3612-11eb-8c74-9ce14edd70e2.gif)

![sdk-element-error](https://user-images.githubusercontent.com/25725586/101145793-2f8ccd00-3612-11eb-9d23-f33c5f21c63d.gif)

**Comment by gcandal** [comment]
@BeeMargarida try and investigate this one, checking if we're calling the `unbindConfigurator` at the right time (destroyed etc), etc.
