### ISSUE TITLE
Initial working Image in Vue

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-sdk-components-vue#6]
## Description

Build a Vue component that wrap [bindImage](https://ripe-sdk-docs.platforme.com/ripe.Ripe.html#bindImage) to build a `ripe-image` component.

Image Props:
* Frame (optional)
* Brand
* Model
* Version
* Parts (optional)
* Size (optional)
* Ripe SDK (optional)

Image Events: `update:parts`, `loading`, `loaded`

If the ripeSdk is not passed as prop, these components will check if `global.ripeSdk` exists and instantiate it if it doesn't. Afterwards, it must `.config` it to apply the options.

These components must have unit tests and public documentation.

**Comment by joamag** [comment]
This is now considered done. @BeeMargarida please do not forget to link the issues so that we can close them automatically ;)
